name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts


      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /var/www/myapp
          REPO_URL: git clone https://github.com/Mustafo746/deploy_ci_cd.git "SAPP_DIR"
        run: |
          ssh $USER@$HOST << EOF
            set -e

            echo "App papka: \$APP_DIR"
            mkdir -p \$APP_DIR
            cd \$APP_DIR

            if [ ! -d ".git" ]; then
              echo "Repo clone qilinyapti"
              git clone \$REPO_URL .
            else
              echo "Repo yangilanmoqda"
              git pull origin main
            fi

            echo "Dependencylar"
            npm install --production

            echo "PM2 start/restart"
            if pm2 list | grep -q myapp; then
              pm2 restart myapp
            else
              pm2 start server.js --name myapp
            fi

            pm2 save
            echo "Deploy tugadi"
          EOF
